[package]
name = "clipping-runtime"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "capinsta-clipping-runtime"
path = "src/main.rs"

[dependencies]
clip-domain = { path = "../clip-domain" }
project-bridge = { path = "../project-bridge" }
shorts-domain = { path = "../shorts-domain" }
transcript-domain = { path = "../transcript-domain" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
