import type { CapinstaTranscriptV1 } from "./types"

export const sampleCapinstaTranscriptV1: CapinstaTranscriptV1 = {
  version: "capinsta.transcript.v1",
  source: {
    assetId: "sample-video-001",
    assetName: "sample-founder-intro.mp4",
    durationSeconds: 6.2,
    mimeType: "video/mp4",
  },
  languageMode: "english",
  provider: {
    name: "sarvam",
    model: "saaras:v3",
    requestId: "sample-request-001",
  },
  clips: [
    {
      id: "cap-001",
      start: 0.42,
      end: 2.18,
      text: "Build the edit",
      wordIds: ["word-001", "word-002", "word-003"],
    },
    {
      id: "cap-002",
      start: 2.32,
      end: 4.65,
      text: "then captions follow",
      wordIds: ["word-004", "word-005", "word-006"],
    },
  ],
  words: [
    {
      id: "word-001",
      text: "Build",
      displayedText: "Build",
      start: 0.42,
      end: 0.86,
      confidence: 0.98,
      provider: "sarvam",
      timingSource: "provider",
    },
    {
      id: "word-002",
      text: "the",
      displayedText: "the",
      start: 0.9,
      end: 1.12,
      confidence: 0.97,
      provider: "sarvam",
      timingSource: "provider",
    },
    {
      id: "word-003",
      text: "edit",
      displayedText: "edit",
      start: 1.16,
      end: 1.94,
      confidence: 0.96,
      provider: "sarvam",
      timingSource: "provider",
    },
    {
      id: "word-004",
      text: "then",
      displayedText: "then",
      start: 2.32,
      end: 2.72,
      confidence: 0.95,
      provider: "sarvam",
      timingSource: "provider",
    },
    {
      id: "word-005",
      text: "captions",
      displayedText: "captions",
      start: 2.78,
      end: 3.58,
      confidence: 0.92,
      provider: "sarvam",
      timingSource: "provider",
    },
    {
      id: "word-006",
      text: "follow",
      displayedText: "follow",
      start: 3.64,
      end: 4.42,
      confidence: 0.9,
      provider: "sarvam",
      timingSource: "provider",
      timingNeedsReview: true,
      timingSourceDetail: "provider_word_low_confidence",
    },
  ],
  stylePreset: {
    id: "word_highlight_box",
    name: "Word Highlight Box",
    renderer: "word_highlight_box",
    styleConfig: {
      activeWordColor: "#FFD43B",
      textColor: "#FFFFFF",
    },
    chunkingConfig: {
      targetWordsPerCaption: 4,
      pauseSplitThreshold: 0.45,
    },
  },
  manualEdits: {
    notes: ["Sample fixture for OpenCut adapter tests."],
  },
  timing: {
    sourceOfTruth: "words",
    generatedAt: "2026-06-15T00:00:00.000Z",
    audioDurationSeconds: 6.2,
    silenceGaps: [{ start: 1.95, end: 2.31, duration: 0.36 }],
    speechSegments: [
      { start: 0.42, end: 1.94, confidence: 0.65 },
      { start: 2.32, end: 4.42, confidence: 0.65 },
    ],
  },
}
