import type { CapinstaCaptionStyleV1 } from "./styleTypes";
import {
	CAPINSTA_CREATOR_FONTS,
	CAPINSTA_FONT_STACKS,
} from "@/capinsta/fonts/captionFontRegistry";

export const CAPINSTA_CAPTION_STYLE_VERSION =
	"capinsta.captionStyle.v1" as const;

export { CAPINSTA_CREATOR_FONTS, CAPINSTA_FONT_STACKS };

export const DEFAULT_CAPINSTA_CAPTION_STYLE: CapinstaCaptionStyleV1 = {
	version: CAPINSTA_CAPTION_STYLE_VERSION,
	presetId: "word_highlight_box",
	presetName: "Word Highlight Box",
	text: {
		fontFamily: "Poppins",
		fontWeight: 900,
		alignment: "center",
		fontSize: 54,
		lineHeight: 1.12,
		maxLines: 2,
		color: "#FFFFFF",
		opacity: 1,
		textTransform: "none",
		letterSpacing: 0,
	},
	background: {
		enabled: true,
		color: "#000000",
		fit: "wrap",
		opacity: 1,
		cornerRadius: 16,
		paddingX: 24,
		paddingY: 14,
		borderEnabled: false,
		borderColor: "#ffffff",
		borderWidth: 0,
		shadowEnabled: false,
		shadowColor: "#000000",
		shadowOpacity: 0.3,
		shadowBlur: 8,
		shadowDistance: 4,
		shadowAngle: 45,
	},
	outline: {
		weight: "none",
		color: "#000000",
		width: 0,
	},
	shadow: {
		enabled: false,
		color: "#000000",
		opacity: 0.3,
		blur: 8,
		distance: 4,
		angle: 45,
	},
	activeWord: {
		color: "#FFD43B",
		backgroundEnabled: false,
		backgroundColor: "#000000",
		backgroundOpacity: 0.35,
		backgroundPaddingX: 6,
		backgroundPaddingY: 2,
		backgroundCornerRadius: 8,
		scale: 1.06,
		glow: false,
	},
	animation: {
		wordEffect: "pop",
		type: "pop",
		transition: "none",
		entrance: "none",
		strength: 0.55,
		speed: 1,
		smoothness: 0.72,
	},
	layout: {
		positionX: 50,
		positionY: 78,
		maxWidth: 82,
		scale: 1,
		opacity: 1,
		rotation: 0,
		safeAreaEnabled: true,
		asymmetricScaleEnabled: false,
		asymmetricScaleStrength: 0,
	},
	effects: {
		randomTiltEnabled: false,
		smartHighlightEnabled: false,
		emphasisGreenColor: "#00FF00",
		emphasisYellowColor: "#FFFF00",
		emphasisRedColor: "#FF0000",
	},
	reveal: {
		duration: 0.28,
		yOffset: 30,
		blur: 25,
		phraseHoldDuration: 0.2,
		hardCut: false,
	},
	lockup: {
		bigFontFamily: "Poppins",
		smallFontFamily: "Poppins",
		bigFontSizePx: 220,
		smallFontSizePx: 104,
		anchorSizeMultiplier: 1.55,
		supportSizeMultiplier: 0.28,
		layoutMode: "auto",
		layoutAsymmetry: 0.45,
		layoutSafeMarginPercent: 8,
		collisionPadding: 8,
		tightness: 0.75,
		showBuildWordBounds: false,
	},
	chunking: {
		maxLines: 2,
		wordsPerCaption: 3,
		charactersPerLine: 34,
		removeFillerWords: false,
		targetWordsPerCaption: 3,
		maxWordsPerCaption: 4,
		minWordsPerCaption: 1,
		maxCharsPerCaption: 34,
		minCaptionDuration: 0.35,
		maxCaptionDuration: 2.2,
		pauseSplitThreshold: 0.45,
		mergeSmallGapThreshold: 0.04,
		targetReadingSpeedCps: 18,
		wordTimingSensitivity: 1,
		minWordDuration: 0.08,
		maxHoldAfterWord: 0.12,
		avoidSingleWordCaptions: true,
		balanceLineLength: true,
	},
};

export function getDefaultCapinstaCaptionStyle(): CapinstaCaptionStyleV1 {
	return structuredClone(DEFAULT_CAPINSTA_CAPTION_STYLE);
}
