"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";

const steps = [["How did you find CapInsta?", ["YouTube", "Instagram", "TikTok", "Twitter / X", "Google Search", "Friend / Referral", "Discord / Community", "Other"]], ["What are you mainly creating?", ["Instagram Reels", "YouTube Shorts", "TikTok Videos", "Podcasts / Talking Head", "Tutorials", "Gaming Clips", "Client Work", "Marketing Ads", "Other"]], ["How experienced are you with video editing?", ["Beginner", "Intermediate", "Advanced", "Professional"]], ["What do you want to achieve with CapInsta?", ["Save editing time", "Create animated captions", "Grow on social media", "Create client content faster", "Repurpose long videos into shorts", "Improve video quality", "Other"]]] as const;
const fields = ["source", "useCase", "experienceLevel", "mainGoal"] as const;
export function ProjectsOnboardingCard({ onDone }: { onDone: () => void }) {
	const [step, setStep] = useState(0); const [answers, setAnswers] = useState<Record<string, string>>({}); const [other, setOther] = useState(""); const [ready, setReady] = useState(false);
	useEffect(() => { fetch("/api/onboarding").then((r) => r.json()).then((d) => { if (!d.completed) setReady(true); else onDone(); }).catch(() => setReady(true)); }, [onDone]);
	if (!ready) return null; const [question, options] = steps[step]; const field = fields[step]; const selected = answers[field];
	const next = async () => { const nextAnswers = { ...answers, [field]: selected }; if (step < steps.length - 1) { setAnswers(nextAnswers); setOther(""); setStep(step + 1); return; } const payload = { source: nextAnswers.source, sourceOther: nextAnswers.source === "Other" ? other : undefined, useCase: nextAnswers.useCase, useCaseOther: nextAnswers.useCase === "Other" ? other : undefined, experienceLevel: nextAnswers.experienceLevel, mainGoal: nextAnswers.mainGoal, mainGoalOther: nextAnswers.mainGoal === "Other" ? other : undefined }; const response = await fetch("/api/onboarding", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (response.ok) onDone(); };
	return <section className="mx-auto flex w-full max-w-[640px] flex-col gap-6 rounded-sm border-2 border-border bg-card px-4 py-10 text-center shadow-[5px_5px_0_var(--shadow-strong)] sm:px-8"><div><p className="text-sm font-bold text-primary">Creator setup · {step + 1}/4</p><h2 className="mt-2 text-2xl font-black">Welcome to CapInsta</h2><p className="mt-1 text-muted-foreground">Help us personalize your experience.</p></div><div className="text-left"><h3 className="mb-3 font-bold">{question}</h3><div className="grid gap-2 sm:grid-cols-2">{options.map((option) => <button key={option} type="button" onClick={() => setAnswers({ ...answers, [field]: option })} className={`rounded-sm border-2 p-3 text-left text-sm font-semibold ${selected === option ? "border-primary bg-primary text-primary-foreground" : "border-border hover:border-primary"}`}>{option}</button>)}</div>{selected === "Other" && <input value={other} onChange={(e) => setOther(e.target.value)} className="mt-3 h-10 w-full rounded-sm border bg-background px-3 text-sm" placeholder="Tell us more" />}</div><Button variant="lime" className="self-center font-black" disabled={!selected || (selected === "Other" && !other.trim())} onClick={next}>{step === 3 ? "Finish setup" : "Continue"}</Button></section>;
}
