import { validatePaperFoldManifest } from "opencut-wasm";
import type {
	PaperFoldParams,
	PaperFoldStyleId,
	PaperFoldStyleManifest,
} from "./types";

const DESIGN_SIZE = 512;
const FRAME_COUNT = 12;
const REPLACEMENT_NOTICE =
	"Developer placeholder generated by Capinsta. Replace with original or properly licensed production artwork.";

const STYLE_NAMES: Record<PaperFoldStyleId, string> = {
	"center-fold": "Center Fold",
	"corner-fold": "Corner Fold",
	"envelope-fold": "Envelope Fold",
	"crumple-fold": "Crumple Fold",
};
const STYLE_IDS: readonly PaperFoldStyleId[] = [
	"center-fold",
	"corner-fold",
	"envelope-fold",
	"crumple-fold",
];

export const PAPER_FOLD_STYLE_MANIFESTS: readonly PaperFoldStyleManifest[] =
	STYLE_IDS.map((id) => ({
		id,
		name: STYLE_NAMES[id],
		version: id === "crumple-fold" ? 2 : 1,
		width: DESIGN_SIZE,
		height: DESIGN_SIZE,
		frameCount: FRAME_COUNT,
		frames: Array.from({ length: FRAME_COUNT }, (_, frame) => ({
			paper: `paper-fold-dev://${id}/paper/${frame}`,
			matte: `paper-fold-dev://${id}/matte/${frame}`,
		})),
		defaultDirection: "right",
		supportsReverse: true,
		assetKind: "generated-placeholder",
		replacementNotice: REPLACEMENT_NOTICE,
	}));

export interface GeneratedFoldFrame {
	paper: CanvasImageSource;
	matte: CanvasImageSource;
}

type Surface = HTMLCanvasElement | OffscreenCanvas;
const frameCache = new Map<string, GeneratedFoldFrame>();
const atlasCache = new Map<string, Surface>();

export function getPaperFoldManifest({
	styleId,
}: {
	styleId: PaperFoldStyleId;
}): PaperFoldStyleManifest {
	return (
		PAPER_FOLD_STYLE_MANIFESTS.find((manifest) => manifest.id === styleId) ??
		PAPER_FOLD_STYLE_MANIFESTS[0]
	);
}

export function validateStyleManifest({
	manifest,
	maxTextureSize = 4096,
}: {
	manifest: PaperFoldStyleManifest;
	maxTextureSize?: number;
}): { valid: boolean; errors: string[] } {
	try {
		const validation: unknown = validatePaperFoldManifest(
			manifest,
			maxTextureSize,
		);
		if (
			typeof validation === "object" &&
			validation !== null &&
			"valid" in validation &&
			typeof validation.valid === "boolean" &&
			"errors" in validation &&
			Array.isArray(validation.errors) &&
			validation.errors.every((message) => typeof message === "string")
		) {
			return { valid: validation.valid, errors: validation.errors };
		}
		throw new Error("Paper Fold manifest validator returned an invalid result");
	} catch (error) {
		return {
			valid: false,
			errors: [
				error instanceof Error
					? error.message
					: "Paper Fold manifest validation failed",
			],
		};
	}
}

export function getGeneratedFoldFrame({
	styleId,
	frameIndex,
	direction,
	origin,
}: {
	styleId: PaperFoldStyleId;
	frameIndex: number;
	direction: PaperFoldParams["foldDirection"];
	origin: PaperFoldParams["foldOrigin"];
}): GeneratedFoldFrame {
	const manifest = getPaperFoldManifest({ styleId });
	const index = Math.min(
		manifest.frameCount - 1,
		Math.max(0, Math.round(frameIndex)),
	);
	const key = `${styleId}:${direction}:${origin}:${index}`;
	const cached = frameCache.get(key);
	if (cached) return cached;

	const progress = index / Math.max(1, manifest.frameCount - 1);
	const matte = createSurface({ width: DESIGN_SIZE, height: DESIGN_SIZE });
	const paper = createSurface({ width: DESIGN_SIZE, height: DESIGN_SIZE });
	drawMatte({
		context: getContext(matte),
		styleId,
		progress,
		direction,
		origin,
	});
	drawPaper({
		context: getContext(paper),
		styleId,
		progress,
		direction,
		origin,
	});
	const generated = { paper, matte };
	frameCache.set(key, generated);
	return generated;
}

export function getGeneratedFoldAtlas({
	styleId,
	direction,
	origin,
}: {
	styleId: PaperFoldStyleId;
	direction: PaperFoldParams["foldDirection"];
	origin: PaperFoldParams["foldOrigin"];
}): {
	canvas: CanvasImageSource;
	columns: number;
	rows: number;
	width: number;
	height: number;
	version: number;
} {
	const manifest = getPaperFoldManifest({ styleId });
	const key = `${styleId}:v${manifest.version}:${direction}:${origin}`;
	const columns = Math.ceil(Math.sqrt(manifest.frameCount));
	const rows = Math.ceil(manifest.frameCount / columns);
	let atlas = atlasCache.get(key);
	if (!atlas) {
		atlas = createSurface({
			width: manifest.width * columns * 2,
			height: manifest.height * rows,
		});
		const context = getContext(atlas);
		for (let index = 0; index < manifest.frameCount; index++) {
			const frame = getGeneratedFoldFrame({
				styleId,
				frameIndex: index,
				direction,
				origin,
			});
			const column = index % columns;
			const row = Math.floor(index / columns);
			context.drawImage(
				frame.paper,
				column * manifest.width,
				row * manifest.height,
			);
			context.drawImage(
				frame.matte,
				manifest.width * columns + column * manifest.width,
				row * manifest.height,
			);
		}
		atlasCache.set(key, atlas);
	}
	return {
		canvas: atlas,
		columns,
		rows,
		width: atlas.width,
		height: atlas.height,
		version: manifest.version,
	};
}

export function clearPaperFoldAssetCache(): void {
	for (const frame of frameCache.values()) {
		closeImageSource(frame.paper);
		closeImageSource(frame.matte);
	}
	frameCache.clear();
	atlasCache.clear();
}

function createSurface({
	width,
	height,
}: {
	width: number;
	height: number;
}): Surface {
	if (typeof OffscreenCanvas !== "undefined") {
		return new OffscreenCanvas(width, height);
	}
	if (typeof document !== "undefined") {
		const canvas = document.createElement("canvas");
		canvas.width = width;
		canvas.height = height;
		return canvas;
	}
	throw new Error("Paper Fold requires OffscreenCanvas or an HTML canvas");
}

function getContext(
	canvas: Surface,
): CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D {
	const context = canvas.getContext("2d");
	if (!context || !("drawImage" in context)) {
		throw new Error("Paper Fold could not create a 2D rendering context");
	}
	return context as
		| CanvasRenderingContext2D
		| OffscreenCanvasRenderingContext2D;
}

function drawMatte({
	context,
	styleId,
	progress,
	direction,
	origin,
}: {
	context: CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D;
	styleId: PaperFoldStyleId;
	progress: number;
	direction: PaperFoldParams["foldDirection"];
	origin: PaperFoldParams["foldOrigin"];
}) {
	context.clearRect(0, 0, DESIGN_SIZE, DESIGN_SIZE);
	context.fillStyle = "#ffffff";
	context.save();
	applyDirectionTransform({ context, direction });
	const minimum = 0.035;
	const reveal = minimum + (1 - minimum) * progress;
	if (styleId === "center-fold") {
		const width = DESIGN_SIZE * reveal;
		context.fillRect((DESIGN_SIZE - width) / 2, 0, width, DESIGN_SIZE);
	} else if (styleId === "corner-fold") {
		const point = originPoint(origin);
		const radius = DESIGN_SIZE * 1.5 * reveal;
		context.beginPath();
		context.arc(point.x, point.y, radius, 0, Math.PI * 2);
		context.fill();
	} else if (styleId === "envelope-fold") {
		const inset = (DESIGN_SIZE / 2) * (1 - reveal);
		context.beginPath();
		context.moveTo(DESIGN_SIZE / 2, inset);
		context.lineTo(DESIGN_SIZE - inset, DESIGN_SIZE / 2);
		context.lineTo(DESIGN_SIZE / 2, DESIGN_SIZE - inset);
		context.lineTo(inset, DESIGN_SIZE / 2);
		context.closePath();
		context.fill();
	} else {
		const geometry = crumpleGeometry({ progress, origin });
		drawIrregularSheetPath({
			context,
			...geometry,
			seed: 811,
			inset: progress >= 0.999 ? -12 : 0,
		});
		context.fill();
	}
	context.restore();
}

function drawPaper({
	context,
	styleId,
	progress,
	direction,
	origin,
}: {
	context: CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D;
	styleId: PaperFoldStyleId;
	progress: number;
	direction: PaperFoldParams["foldDirection"];
	origin: PaperFoldParams["foldOrigin"];
}) {
	context.clearRect(0, 0, DESIGN_SIZE, DESIGN_SIZE);
	context.save();
	applyDirectionTransform({ context, direction });
	const fold = 1 - progress;
	const gradient = context.createLinearGradient(0, 0, DESIGN_SIZE, DESIGN_SIZE);
	gradient.addColorStop(0, "rgba(255,252,242,0.96)");
	gradient.addColorStop(0.48, "rgba(209,198,175,0.92)");
	gradient.addColorStop(0.52, "rgba(255,250,235,0.96)");
	gradient.addColorStop(1, "rgba(174,160,137,0.9)");
	context.fillStyle = gradient;
	context.strokeStyle = "rgba(83,69,51,0.3)";
	context.lineWidth = 2;
	if (styleId === "center-fold") {
		const band = Math.max(2, DESIGN_SIZE * fold * 0.22);
		context.fillRect(DESIGN_SIZE / 2 - band, 0, band * 2, DESIGN_SIZE);
		context.strokeRect(DESIGN_SIZE / 2 - band, 0, band * 2, DESIGN_SIZE);
	} else if (styleId === "corner-fold") {
		const point = originPoint(origin);
		const size = Math.max(2, DESIGN_SIZE * fold * 0.62);
		context.beginPath();
		context.moveTo(point.x, point.y);
		context.lineTo(point.x === 0 ? size : DESIGN_SIZE - size, point.y);
		context.lineTo(point.x, point.y === 0 ? size : DESIGN_SIZE - size);
		context.closePath();
		context.fill();
		context.stroke();
	} else if (styleId === "envelope-fold") {
		const depth = Math.max(2, DESIGN_SIZE * fold * 0.48);
		for (const points of [
			[
				[0, 0],
				[DESIGN_SIZE, 0],
				[DESIGN_SIZE / 2, depth],
			],
			[
				[0, DESIGN_SIZE],
				[DESIGN_SIZE, DESIGN_SIZE],
				[DESIGN_SIZE / 2, DESIGN_SIZE - depth],
			],
		] as const) {
			context.beginPath();
			context.moveTo(points[0][0], points[0][1]);
			context.lineTo(points[1][0], points[1][1]);
			context.lineTo(points[2][0], points[2][1]);
			context.closePath();
			context.fill();
			context.stroke();
		}
	} else {
		drawCrumpledRevealPaper({ context, progress, origin });
	}
	context.restore();
}

/**
 * Original procedural crumpled-paper geometry. The silhouette grows in a few
 * readable steps so frame-held playback resembles stop-motion paper footage.
 */
export function crumpleGeometry({
	progress,
	origin,
}: {
	progress: number;
	origin: PaperFoldParams["foldOrigin"];
}): {
	centerX: number;
	centerY: number;
	width: number;
	height: number;
	roughness: number;
} {
	const clamped = Math.min(1, Math.max(0, progress));
	const growth = Math.min(1, 1 - (1 - clamped) ** 2.65);
	const anchor = originPoint(origin);
	const centerPull = 1 - growth;
	return {
		centerX: DESIGN_SIZE / 2 + (anchor.x - DESIGN_SIZE / 2) * centerPull * 0.42,
		centerY: DESIGN_SIZE / 2 + (anchor.y - DESIGN_SIZE / 2) * centerPull * 0.42,
		width: DESIGN_SIZE * (0.15 + growth * 0.91),
		height: DESIGN_SIZE * (0.18 + growth * 0.88),
		roughness: DESIGN_SIZE * (0.018 + (1 - growth) * 0.035),
	};
}

function drawCrumpledRevealPaper({
	context,
	progress,
	origin,
}: {
	context: CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D;
	progress: number;
	origin: PaperFoldParams["foldOrigin"];
}) {
	const geometry = crumpleGeometry({ progress, origin });
	const growth = Math.min(1, geometry.width / (DESIGN_SIZE * 1.06));
	const outer = {
		context,
		...geometry,
		seed: 811,
		inset: 0,
	};

	context.save();
	drawIrregularSheetPath(outer);
	context.clip();
	const base = context.createRadialGradient(
		geometry.centerX - geometry.width * 0.15,
		geometry.centerY - geometry.height * 0.2,
		2,
		geometry.centerX,
		geometry.centerY,
		Math.max(geometry.width, geometry.height) * 0.7,
	);
	base.addColorStop(0, "#fffef9");
	base.addColorStop(0.42, "#e8e5dc");
	base.addColorStop(0.72, "#faf8f0");
	base.addColorStop(1, "#aaa69c");
	context.fillStyle = base;
	context.fillRect(0, 0, DESIGN_SIZE, DESIGN_SIZE);

	for (let index = 0; index < 24; index++) {
		const angle = seededUnit(index * 13 + 5) * Math.PI * 2;
		const radius = seededUnit(index * 17 + 19) * 0.48;
		const x = geometry.centerX + Math.cos(angle) * geometry.width * radius;
		const y = geometry.centerY + Math.sin(angle) * geometry.height * radius;
		const size =
			Math.min(geometry.width, geometry.height) *
			(0.09 + seededUnit(index * 29 + 7) * 0.2);
		context.beginPath();
		context.moveTo(x, y - size);
		context.lineTo(x + size * 0.85, y + size * 0.65);
		context.lineTo(x - size * 0.8, y + size * 0.5);
		context.closePath();
		const shade = Math.round(174 + seededUnit(index * 31 + 3) * 76);
		context.fillStyle = `rgba(${shade},${shade},${Math.max(0, shade - 5)},${0.16 + (1 - growth) * 0.34})`;
		context.fill();
	}
	context.restore();

	const reveal = Math.max(0, progress - 0.055) / 0.945;
	if (reveal > 0) {
		const rim = 7 + (1 - reveal) * 18;
		context.save();
		context.globalCompositeOperation = "destination-out";
		drawIrregularSheetPath({
			context,
			...geometry,
			width: Math.max(1, geometry.width - rim * 2),
			height: Math.max(1, geometry.height - rim * 2),
			roughness: geometry.roughness * 0.72,
			seed: 947,
			inset: 0,
		});
		context.fillStyle = "#000000";
		context.fill();
		context.restore();
	}

	context.save();
	drawIrregularSheetPath(outer);
	context.clip();
	context.globalCompositeOperation = "source-over";
	context.lineCap = "round";
	for (let index = 0; index < 18; index++) {
		const startAngle = seededUnit(index * 41 + 13) * Math.PI * 2;
		const endAngle = startAngle + (seededUnit(index * 43 + 17) - 0.5) * 1.8;
		const radius = 0.18 + seededUnit(index * 47 + 23) * 0.42;
		const startX =
			geometry.centerX + Math.cos(startAngle) * geometry.width * radius * 0.45;
		const startY =
			geometry.centerY + Math.sin(startAngle) * geometry.height * radius * 0.45;
		const endX = geometry.centerX + Math.cos(endAngle) * geometry.width * 0.48;
		const endY = geometry.centerY + Math.sin(endAngle) * geometry.height * 0.48;
		context.beginPath();
		context.moveTo(startX, startY);
		context.quadraticCurveTo(
			(startX + endX) / 2 +
				(seededUnit(index * 53 + 29) - 0.5) * geometry.width * 0.16,
			(startY + endY) / 2 +
				(seededUnit(index * 59 + 31) - 0.5) * geometry.height * 0.16,
			endX,
			endY,
		);
		context.strokeStyle =
			index % 2 === 0
				? `rgba(72,68,60,${0.12 + (1 - growth) * 0.2})`
				: `rgba(255,255,250,${0.2 + (1 - growth) * 0.24})`;
		context.lineWidth = 1.2 + (1 - growth) * 2.8;
		context.stroke();
	}
	context.restore();
}

function drawIrregularSheetPath({
	context,
	centerX,
	centerY,
	width,
	height,
	roughness,
	seed,
	inset,
}: {
	context: CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D;
	centerX: number;
	centerY: number;
	width: number;
	height: number;
	roughness: number;
	seed: number;
	inset: number;
}) {
	const halfWidth = Math.max(1, width / 2 - inset);
	const halfHeight = Math.max(1, height / 2 - inset);
	const pointsPerEdge = 12;
	const points: Array<[number, number]> = [];
	for (let index = 0; index < pointsPerEdge; index++) {
		const t = index / pointsPerEdge;
		points.push([
			centerX - halfWidth + t * halfWidth * 2,
			centerY - halfHeight + (seededUnit(seed + index) - 0.5) * roughness,
		]);
	}
	for (let index = 0; index < pointsPerEdge; index++) {
		const t = index / pointsPerEdge;
		points.push([
			centerX + halfWidth + (seededUnit(seed + 101 + index) - 0.5) * roughness,
			centerY - halfHeight + t * halfHeight * 2,
		]);
	}
	for (let index = 0; index < pointsPerEdge; index++) {
		const t = index / pointsPerEdge;
		points.push([
			centerX + halfWidth - t * halfWidth * 2,
			centerY + halfHeight + (seededUnit(seed + 211 + index) - 0.5) * roughness,
		]);
	}
	for (let index = 0; index < pointsPerEdge; index++) {
		const t = index / pointsPerEdge;
		points.push([
			centerX - halfWidth + (seededUnit(seed + 307 + index) - 0.5) * roughness,
			centerY + halfHeight - t * halfHeight * 2,
		]);
	}

	context.beginPath();
	context.moveTo(points[0][0], points[0][1]);
	for (let index = 1; index < points.length; index++) {
		const current = points[index];
		const next = points[(index + 1) % points.length];
		context.quadraticCurveTo(
			current[0],
			current[1],
			(current[0] + next[0]) / 2,
			(current[1] + next[1]) / 2,
		);
	}
	context.closePath();
}

function applyDirectionTransform({
	context,
	direction,
}: {
	context: CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D;
	direction: PaperFoldParams["foldDirection"];
}) {
	if (direction === "left") {
		context.translate(DESIGN_SIZE, 0);
		context.scale(-1, 1);
	} else if (direction === "up") {
		context.translate(0, DESIGN_SIZE);
		context.rotate(-Math.PI / 2);
	} else if (direction === "down") {
		context.translate(DESIGN_SIZE, 0);
		context.rotate(Math.PI / 2);
	}
}

function originPoint(origin: PaperFoldParams["foldOrigin"]) {
	if (origin === "top-left") return { x: 0, y: 0 };
	if (origin === "top-right") return { x: DESIGN_SIZE, y: 0 };
	if (origin === "bottom-left") return { x: 0, y: DESIGN_SIZE };
	if (origin === "bottom-right") return { x: DESIGN_SIZE, y: DESIGN_SIZE };
	return { x: DESIGN_SIZE / 2, y: DESIGN_SIZE / 2 };
}

function seededUnit(seed: number) {
	let value = seed | 0;
	value = Math.imul(value ^ (value >>> 16), 0x7feb352d);
	value = Math.imul(value ^ (value >>> 15), 0x846ca68b);
	return ((value ^ (value >>> 16)) >>> 0) / 0xffffffff;
}

function closeImageSource(source: CanvasImageSource) {
	if ("close" in source && typeof source.close === "function") source.close();
}
